
services:
  revit-code:
    build:
      context: .
      dockerfile: ./Revit-Agent/agent-revit-coder/Dockerfile
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      # Montamos el proyecto entero para desarrollo en vivo.
      # Los cambios en CUALQUIER archivo se reflejarán.
      - .:/app
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  revit-orch:
    build:
      context: .
      dockerfile: ./Revit-Agent/agent-revit-orchestrator/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    depends_on:
      - revit-code