FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime

# 1. Instalar dependencias del sistema y Git
RUN apt-get update && apt-get install -y \
    git \
    git-lfs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 2. Configurar el directorio de trabajo
WORKDIR /app

# 3. Copiar solo los archivos de requisitos primero para aprovechar la caché
COPY requirements.txt .

# 4. Instalar las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copiar todo el resto del código del proyecto (respetando .dockerignore)
COPY . .

# 6. Iniciar sesión en Hugging Face (usando un token pasado como argumento)
ARG HF_TOKEN
RUN huggingface-cli login --token $HF_TOKEN

CMD ["/bin/bash"]