FROM nvcr.io/nvidia/pytorch:24.01-py3

# 1. Instalar dependencias del sistema
RUN apt-get update && apt-get install -y git git-lfs && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 2. Copiar el archivo de requisitos
COPY requirements.txt .

# 3. Instalar las dependencias de Python. 
# Sin --no-deps. Dejamos que pip haga su trabajo, guiado por la versión fijada.
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copiar el resto del código del proyecto
COPY . .

# 5. Iniciar sesión en Hugging Face
ARG HF_TOKEN
RUN huggingface-cli login --token $HF_TOKEN

CMD ["/bin/bash"]