services:
  revit-code:
    build:
      context: .
      dockerfile: ./Revit-Agent/agent-revit-coder/Dockerfile
    runtime: nvidia
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      # Monta todo el proyecto en /app para desarrollo en vivo.
      # Esto asegura que todas las rutas (al modelo, a shared_libs) funcionan.
      - .:/app
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  revit-orch:
    build:
      context: .
      dockerfile: ./Revit-Agent/agent-revit-orchestrator/Dockerfile
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    depends_on:
      - revit-code